name: Test (PR)
on:
  pull_request:

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      # ...
      - uses: actions/checkout@v3
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: "1.0.28"
      - run: bun install
      - run: bun run build
      - run: bun turbo build lint test typecheck
